baseURL = "https://bear-jordan.com/"
languageCode = "en-US"
title = "Bear Jordan"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Bear Jordan"
  description = "Personal Portolio"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "bear-jordan"
  Email         = "bearjordan@gmail.com"
  Twitter       = "bear_jordan_"
  LinkedIn      = "bear-jordan"

## Main Menu
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/documents/bear_jordan.pdf"
